#!/bin/bash
# ASTRA Cumulative Analysis - Quick Start Guide
# This script demonstrates running ASTRA with cumulative multi-tool scanning

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║           ASTRA - AI-Driven Security Scanning Orchestrator        ║"
echo "║              Cumulative Analysis Configuration Ready              ║"
echo "╚════════════════════════════════════════════════════════════════════╝"

echo ""
echo "✓ System Verification: 16/16 checks passed"
echo "✓ Initial Scanners: nmap, whatweb, nuclei, nikto"
echo "✓ Cumulative Analysis: Enabled"
echo "✓ AI Planning: Gemini 2.5 Flash integration"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "USAGE OPTIONS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

echo ""
echo "1. BASIC USAGE (with default scanners including nikto):"
echo "   python orchestrator/main.py scanme.nmap.org --mode dynamic"
echo ""
echo "   This runs:"
echo "   • nmap scanme.nmap.org"
echo "   • [in parallel] whatweb, nuclei, nikto on discovered services"
echo "   • AI analyzes ALL findings cumulatively"
echo "   • AI recommends next tools (up to 3 iterations)"
echo ""

echo "2. CUSTOM SCANNERS (override default):"
echo "   python orchestrator/main.py scanme.nmap.org --mode dynamic --enable nmap,whatweb"
echo ""
echo "   This runs ONLY nmap and whatweb (no nuclei, no nikto)"
echo ""

echo "3. DRY RUN (see what commands would execute without running):"
echo "   python orchestrator/main.py scanme.nmap.org --mode dynamic --dry-run"
echo ""
echo "   This shows all commands that would run without actually executing them"
echo ""

echo "4. STATIC MODE (no AI-driven iteration):"
echo "   python orchestrator/main.py scanme.nmap.org --mode static"
echo ""
echo "   This runs only the initial scanners without AI recommendations"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "WHAT HAPPENS DURING DYNAMIC EXECUTION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

echo ""
echo "Iteration 1:"
echo "  1. Run nmap (discover ports/services/versions)"
echo "  2. Run whatweb, nuclei, nikto in parallel (extract technologies, find vulns, check web config)"
echo "  3. Collect 40-100+ findings from all 4 tools"
echo "  4. AI analyzes ALL cumulative findings"
echo "  5. AI generates holistic strategy (e.g., 'Found WordPress 5.x with known vulns')"
echo "  6. AI recommends 3-5 next tools (e.g., wpscan for WordPress)"
echo ""

echo "Iteration 2:"
echo "  1. Run AI-recommended tools (e.g., wpscan, nmap-ssh-scripts)"
echo "  2. Collect new findings"
echo "  3. AI analyzes ALL PREVIOUS + NEW findings together (100-200+ total)"
echo "  4. AI generates updated strategy based on expanded knowledge"
echo "  5. AI recommends more tools if vulnerabilities warrant deeper investigation"
echo ""

echo "Iteration 3 (if needed):"
echo "  1. Run additional recommended tools"
echo "  2. Final comprehensive analysis"
echo "  3. Complete vulnerability picture assembled"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "EXPECTED OUTPUT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

echo ""
echo "[~] Running initial group: ['nmap']"
echo "[~] nmap -sS -sV -T4 -oX orchestrator/output/raw/... scanme.nmap.org"
echo ""
echo "[~] Running initial group: ['whatweb', 'nuclei', 'nikto']"
echo "[~] whatweb -a 3 --log-json ... http://scanme.nmap.org:80"
echo "[~] nuclei -target http://scanme.nmap.org:80 ..."
echo "[~] nikto -h http://scanme.nmap.org:80 ..."
echo ""
echo "[*] Iteration 1: Collected 47 findings"
echo "[AI] Analyzing 47 cumulative findings from all scans..."
echo "[AI] Previously executed tools: {'nmap', 'whatweb', 'nuclei', 'nikto'}"
echo "[AI] Strategy: Apache 2.4.41 with PHP 7.4.3. Found potential path traversal in backup..."
echo "[AI] Recommending 3 actions:"
echo "     - nmap-ssh-scripts: Deep SSH enumeration (found port 22 open)"
echo "     - dirb: Directory brute-force (found web server)"
echo "     - sqlmap: SQL injection testing (found potential parameter injection)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "KEY FILES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

echo ""
echo "Configuration:"
echo "  • orchestrator/core/registry.py          (scanner definitions)"
echo "  • orchestrator/core/parsers.py           (output parsing + nikto)"
echo "  • orchestrator/core/ai/planning_agent.py (AI analysis logic)"
echo ""

echo "Execution:"
echo "  • orchestrator/main.py                   (entry point)"
echo "  • orchestrator/core/engine.py            (orchestration engine)"
echo "  • orchestrator/core/runner.py            (command execution)"
echo ""

echo "Data:"
echo "  • orchestrator/output/raw/               (scanner outputs)"
echo "  • CUMULATIVE_ANALYSIS_SETUP.md           (detailed documentation)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "REQUIREMENTS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

echo ""
echo "✓ Python 3.10+ installed"
echo "✓ Virtual environment activated"
echo "✓ Requirements installed: pip install -r requirements.txt"
echo "✓ GEMINI_API_KEY set in .env file"
echo "✓ Security tools installed: nmap, whatweb, nuclei, nikto"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "CUMULATIVE ANALYSIS BENEFITS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

echo ""
echo "1. HOLISTIC UNDERSTANDING"
echo "   • AI sees complete vulnerability picture, not individual findings"
echo "   • Cross-tool correlations (e.g., nmap+whatweb+nuclei together reveal more)"
echo ""

echo "2. INTELLIGENT RECOMMENDATIONS"
echo "   • AI determines WHAT tools to run and with WHAT flags"
echo "   • Recommendations improve with each iteration as AI learns"
echo ""

echo "3. EFFICIENT SCANNING"
echo "   • No redundant scanning"
echo "   • AI prioritizes high-impact tools based on findings"
echo "   • Parallel execution where possible"
echo ""

echo "4. PROGRESSIVE DISCOVERY"
echo "   • Initial scan finds basics"
echo "   • Iteration 2 digs deeper into specific services/vulnerabilities"
echo "   • Iteration 3 focuses on exploitation paths"
echo ""

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║  Ready to scan! Run: python orchestrator/main.py <target>         ║"
echo "║                     --mode dynamic                                ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""
